In [ ]:
text = "strings are a fundamental data type"
capitalized_text = text.capitalize()
print(capitalized_text)

Strings are a fundamental data type

In [ ]:
text = "Hello World"
upper_text = text.upper()
lower_text = text.lower()
print(upper_text)  # Output: "HELLO WORLD"
print(lower_text)  # Output: "hello world"

HELLO WORLD
hello world

In [ ]:
text = "   Hello, World!   "
stripped_text = text.strip()  # Removes leading/trailing spaces
print(stripped_text)  # Output: "Hello, World!"

Hello, World!

In [ ]:
text = "Hello, World, World"
new_text = text.replace("World", "Python")
print(new_text)

Hello, Python, Python

In [ ]:
mystr1="This is 5 days FDP program on Data"
mystr2 = 'at KG college of Arts & Science'
#capitalize
print(mystr1.capitalize())
#upper&lower
upper_text = mystr1.upper()
lower_text = mystr1.lower()
print("upper Text: ",upper_text)
print("Lower Text: ",lower_text)
#spilit
words=mystr1.split()
print("spilit method",words)
#join
joined='/'.join(mystr1)
print("joined text : ",joined)
#replace
new_text = mystr1.replace("FDP", "Faculty Development Program")
print("Replace method : ",new_text)
#starts with and ends with
starts_with_hello = mystr1.startswith("days")
ends_with_world = mystr1.endswith("python")
print("Strats with",starts_with_hello)
print("Ends with",ends_with_world)


#string concatenation
concatenated_str = mystr1 + mystr2
print(concatenated_str)
#substring
print("Substring : ",mystr1[0:7])

#length of both the original mystr1 and the sliced substring
len_mystr1 = len(mystr1)
len_substring = len(mystr1[0:7])
print("Length of mystr1:", len_mystr1)
print("Length of substring: " ,len_substring)

This is 5 days fdp program on data
upper Text:  THIS IS 5 DAYS FDP PROGRAM ON DATA
Lower Text:  this is 5 days fdp program on data
spilit method ['This', 'is', '5', 'days', 'FDP', 'program', 'on', 'Data']
joined text :  T/h/i/s/ /i/s/ /5/ /d/a/y/s/ /F/D/P/ /p/r/o/g/r/a/m/ /o/n/ /D/a/t/a
Replace method :  This is 5 days Faculty Development Program program on Data
Strats with False
Ends with False
This is 5 days FDP program on Dataat KG college of Arts & Science
Substring :  This is
Length of mystr1: 34
Length of substring:  7

In [ ]:
file = open("Newone.txt", "w")
print("created")

# Writing data to the file
file.write("Hello, World!")

# Closing the file
file.close()

# Opening a file in read mode
file = open("Newone.txt", "r")

# Reading the entire content
content = file.read()
print(content)

created
Hello, World!

In [ ]:
# Opening a file in append mode
file = open("sample.txt", "a")
dict={"name":"Vara","age":28}
# with open("sample.txt","w") as f:
#   f.write(str(dict))
# with open("sample.txt", "r") as f:
#     print(f.read())
# with open("sample.txt", "a+") as f:
#     f.write("Marks: 90")
#     f.seek(0)
#     print(f.read())
file = open("sample.txt", "r")
print(file.readline())
print(file.readline())
file.close()

file = open("sample.txt", "r")
data = file.readlines()
print(data)
file.close()

# Appending data to the file
# file.write("\nThis is a new line.")
# print("successfully added")
# Closing the file
file.close()

{'name': 'Vara', 'age': 28}Marks: 90

["{'name': 'Vara', 'age': 28}Marks: 90"]

In [ ]:
with open("IMG_20240820_074852.jpg", "rb") as file:
    binary_data = file.read()
    print("original image fetched")

# Writing binary data to a file
with open("copy_image.jpg", "wb") as file:
    file.write(binary_data)
    print("copied successfully")

original image fetched
copied successfully

In [ ]:
import csv
# Writing data to a CSV file
with open("Sample_csv.csv", "a", newline="") as csvfile:
     writer = csv.writer(csvfile)
     writer.writerow(["parabu", 100])


with open("Sample_csv.csv", "r") as file:
    print(file.read())

print("Written done")
    # csv_writer = csv.writer(csvfile)
    # csv_writer.writerow(["Name", "Age"])
    # csv_writer.writerow(["Bhaskar", 34])
    # csv_writer.writerow(["Vinoth", 34])
    # csv_writer.writerow(["Senthil", 37])
    # csv_writer.writerow(["Venkatesh", 34])


# Reading data from a CSV file
# with open("Sample_csv.csv", "r") as csvfile:
#     csv_reader = csv.reader(csvfile)
#     for row in csv_reader:
#         print(row)
#         print("done reading")

Nani,100
Gowri,80
Nilasri,90
parabu,100

Written done

In [ ]:
import json
# Writing data to a JSON file
data = [{"name": "Alice", "age": 30},{"name": "Gowri", "age": 8}]
with open("data.json", "w") as jsonfile:
    json.dump(data, jsonfile)

# Reading data from a JSON file
with open("data.json", "r") as jsonfile:
    loaded_data = json.load(jsonfile)
    print(loaded_data)

[{'name': 'Alice', 'age': 30}, {'name': 'Gowri', 'age': 8}]

In [ ]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
# list
list1=[10,20,30]
list2 = [1,2,3]
print(list1+list2)
#array
a=np.array(list1)
b=np.array(list2)
print(a+b)

arr=np.array([10,20,30,40],[50,60,70,80])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)


marks = np.array([100 , 70, 80, 90, 85, 75])
print("First Student:", marks[0])
print("Last Student:", marks[-1])
print("Top 3 Marks:", marks[1:4])


# marks =np.array([10,20,30],[40,50,60])
# print(marks)

SyntaxError: invalid syntax (1571514822.py, line 18)

In [ ]:
import numpy as np

num = "12,25,36,78,69,45,18,27,28,42"
arr = np.array(num.split(','),dtype=int)

print(arr)
print(type(arr))

[12 25 36 78 69 45 18 27 28 42]
<class 'numpy.ndarray'>

In [ ]:
data = np.array([
	[10, 20, 30],
	[40, 50, 60]
])
print(data[0, 1])
print(data[:, 1])

20
[20 50]

In [ ]:
arr = np.array([10, 20, 30, 40])
print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Mean:", np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviaition:",np.std(arr))

Sum: 100
Max: 40
Min: 10
Mean: 25.0
Median: 25.0
Standard Deviaition: 11.180339887498949

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(3, 2)
print(new_arr)
print(new_arr.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]

In [ ]:
a = np.arange(12).reshape(4, 3)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.dtype.name)
print(a.size)
print(a.itemsize)
print(type(a))
print(type(a.dtype))
print(type(a.dtype.name))
print(np.arange(1, 10, 2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
2
int64
int64
12
8
<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int64DType'>
<class 'str'>
[1 3 5 7 9]

In [ ]:
arr = np.array([10, 20, 30])
copy_arr = arr.copy()
view_arr = arr.view()
arr[0] = 99
print("Original:", arr)
print("Copy:", copy_arr)   # Not affected
print("View:", view_arr)   # Affected

Original: [99 20 30]
Copy: [10 20 30]
View: [99 20 30]

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a, axis=1))
print(np.sum(a, axis=0))

[ 6 15]
[5 7 9]

In [ ]:
my_array=np.array([43,24,88,22])
# print("Max:", np.max(my_array>=50))
print("Numbers > 50 ", my_array[my_array >50])

my_array=np.array([2,3,10,5,7,1,6,4,8,9,11,23,12,0,15])
filtered_array = my_array[(my_array < 5) | (my_array > 9)]
print(filtered_array)

# Filter Values Contained in List​
#filter for values that are equal to 2, 3, 5, or 12​

target_values = [2, 3, 5, 12]
filtered_list = [x for x in my_array if x in target_values]
# print(filtered_list)
result = np.array(filtered_list)
print(result)

Numbers > 50  [88]
[ 2  3 10  1  4 11 23 12  0 15]
[ 2  3  5 12]

In [ ]:
arr = np.array([5, 2, 9, 1, 7])
# Sort in descending order
sorted_desc = np.sort(arr)[::-1]
print("Original array:", arr)
print("Sorted descending:", sorted_desc)

Original array: [5 2 9 1 7]
Sorted descending: [9 7 5 2 1]

In [ ]:
import numpy as np
x=np.array([[1,4,2,33],[9,13,61,1],[43,24,88,22]])
print(x)
y=np.sort(x)
print(y)
z=np.sort(x,axis=None)
print(z)
p=np.sort(x,axis=0)
print(p)
q=np.sort(x,axis=1)
print(q)

[[ 1  4  2 33]
 [ 9 13 61  1]
 [43 24 88 22]]
[[ 1  2  4 33]
 [ 1  9 13 61]
 [22 24 43 88]]
[ 1  1  2  4  9 13 22 24 33 43 61 88]
[[ 1  4  2  1]
 [ 9 13 61 22]
 [43 24 88 33]]
[[ 1  2  4 33]
 [ 1  9 13 61]
 [22 24 43 88]]

In [ ]:
import numpy as np
# Define structured array data type
dtype1 = [
	('name', 'S10'),	# Fixed-length string (10 bytes)
	('height', float),  # Height as float
	('age', int),   	# Age as integer
	('gender', 'S10')   # Gender as string
]
# Data values
values = [
	('Shubham', 5.9, 23, 'M'),
	('Arpita', 5.6, 23, 'F'),
	('Vaishali', 5.2, 30, 'F')
]
# Create structured array
x = np.array(values, dtype=dtype1)
print("Original array:")
print(x)

# Sort by age
y = np.sort(x, order='age')
print("\nSorted by age:")
print(y)
# Sort by age, then height
z = np.sort(x, order=['age', 'height'])
print("\nSorted by age, then height:")
print(z)

Original array:
[(b'Shubham', 5.9, 23, b'M') (b'Arpita', 5.6, 23, b'F')
 (b'Vaishali', 5.2, 30, b'F')]

Sorted by age:
[(b'Arpita', 5.6, 23, b'F') (b'Shubham', 5.9, 23, b'M')
 (b'Vaishali', 5.2, 30, b'F')]

Sorted by age, then height:
[(b'Arpita', 5.6, 23, b'F') (b'Shubham', 5.9, 23, b'M')
 (b'Vaishali', 5.2, 30, b'F')]

In [ ]:
a = "How you doing?"
y = np.char.split(a)
print(y)

['How', 'you', 'doing?']

In [ ]:
x = "We, very happily, welcome you all!"
out = np.char.split(x, sep=',', maxsplit=3)
print(out)

['We', ' very happily', ' welcome you all!']

In [ ]:
inp = np.array(['Apple', 'Python', 'NumPy', 'StudyTonight'])
sep = np.array(['***'])
output = np.char.join(sep, inp)
print(output)

['A***p***p***l***e' 'P***y***t***h***o***n' 'N***u***m***P***y'
 'S***t***u***d***y***T***o***n***i***g***h***t']

In [ ]:
a = np.char.join(':', 'MakeupArtist')
print(a)

M:a:k:e:u:p:A:r:t:i:s:t

In [1]:
import numpy as np
a = np.array([1,2,np.nan,4])
print(np.isnan(a))
b=np.nan_to_num(a)
print(b)

[False False  True False]
[1. 2. 0. 4.]

In [8]:
import random
x=[33,45,67,12]
random.shuffle(x)
print(x)

[12, 67, 33, 45]

In [10]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))
print(b.T)
print(np.linalg.det(a))

[[19 22]
 [43 50]]
[[5 7]
 [6 8]]
-2.0000000000000004

In [36]:
import numpy as np
import random
# x= random.randint(1,50)
# print("random no:" , x)
a=np.random.randint(1,50,(4,5))
print("matrix 4*5 : ",a)
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Mean:", np.mean(a))

#generate 5 elements in arr
b=np.random.randint(1,5,size=5)
print(b)
sorted = np.sort(b)
print("sorted :",sorted)

arr = np.array([5, 12, 3, 25, 7, 18])
greater=arr[arr>10]
print(greater)

matrix 4*5 :  [[15 22 29 30 34]
 [10 44 22 44 47]
 [29 34  4 32 24]
 [41 46 40 35 21]]
Max: 47
Min: 4
Mean: 30.15
[1 4 2 2 4]
sorted : [1 2 2 4 4]
[12 25 18]

In [37]:
import numpy as np
a = np.array([1,2,np.nan,4])
print(np.isnan(a))
b=np.nan_to_num(a)
print(b)

[False False  True False]
[1. 2. 0. 4.]

In [39]:
import numpy as np
data = np.array([10, np.nan, 20, np.nan, 30])
# 1. Remove NaNs (The ~ operator means 'NOT')
clean_data = data[~np.isnan(data)]
print(clean_data)
# Output: [10. 20. 30.]

# 2. Replace NaNs with a default value (like 0)
data[np.isnan(data)] = 0
print(data)
# Output: [10.  0. 20.  0. 30.]
mean=np.mean()
print(mean)

[10. 20. 30.]
[10.  0. 20.  0. 30.]
12.0

In [42]:
import numpy as np
income = np.array([45, 120, 30, 85, 200, 60])
income_min = income.min()
income_max = income.max()
print("income_min",income_min)
print("income_max",income_max)
normalized_income = (income - income_min) / (income_max - income_min)
print("Normalized Income:\n", np.round(normalized_income, 2))

income_min 30
income_max 200
Normalized Income:
 [0.09 0.53 0.   0.32 1.   0.18]

In [43]:
import numpy as np
scores = np.array([42, 85, 67, 23, 90, 51])
status = np.where(scores >= 50, "Pass", "Fail")
print(status)
for score, outcome in zip(scores, status):
    print(f"Score: {score} -> Result: {outcome}")

['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']
Score: 42 -> Result: Fail
Score: 85 -> Result: Pass
Score: 67 -> Result: Pass
Score: 23 -> Result: Fail
Score: 90 -> Result: Pass
Score: 51 -> Result: Pass

In [67]:
import numpy as np

#array
dirty_temps = np.array([22.5, np.nan, 100.2, 19.8, -85.0, 25.1, np.nan, 21.0])

#Mark sensor errors as NaN
dirty_temps[(dirty_temps < -50) | (dirty_temps > 60)] = np.nan

#Calculate average of valid temperatures
avg_temp = np.nanmean(dirty_temps)

#Replace NaN values with the average
dirty_temps[np.isnan(dirty_temps)] = avg_temp

#Normalize using Min-Max Scaling
min_temp = np.min(dirty_temps)
max_temp = np.max(dirty_temps)

normalized_temps = (dirty_temps - min_temp) / (max_temp - min_temp)

print("Average Temperature:", avg_temp)
print("Cleaned Temperatures:", dirty_temps)
print("Normalized Temperatures:", normalized_temps)

Average Temperature: 22.1
Cleaned Temperatures: [22.5 22.1 22.1 19.8 22.1 25.1 22.1 21. ]
Normalized Temperatures: [0.50943396 0.43396226 0.43396226 0.         0.43396226 1.
 0.43396226 0.22641509]

In [54]:
import numpy as np
import pandas as pd
x=pd.Series(data=[2,4,6,8])
y=pd.Series(data=[11.2,18.6,22.5], index=['a','b','c'])
print(x.index)
print(x.values)
print(y.index)
print(y.values)
print(y['b'])

RangeIndex(start=0, stop=4, step=1)
[2 4 6 8]
Index(['a', 'b', 'c'], dtype='object')
[11.2 18.6 22.5]
18.6

In [57]:
import numpy as np
import pandas as pd
a=pd.Series(data=[1,2,3,4])
b=pd.Series(data=[4.9,8.2,5.6],
index=['x','y','z'])
print(a.dtype)
print(a.values.itemsize)
print(b.dtype)
print(b.values.itemsize)

int64
8
float64
8

In [58]:
import numpy as np
import pandas as pd
a=pd.Series(data=[1,2,3,np.nan])
b=pd.Series(data=[4.9,8.2,5.6],index=['x','y','z'])
c=pd.Series()
print(a.empty,b.empty,c.empty)
print(a.hasnans,b.hasnans,c.hasnans)
print(len(a),len(b))
print(a.count( ),b.count( ))

False False True
True False False
4 3
3 3

In [60]:
import pandas as pd
lst = ['FRIEND','IN','NEED','IS','A','FRIEND','IN','DEED']

df = pd.DataFrame(lst)
print(df)

        0
0  FRIEND
1      IN
2    NEED
3      IS
4       A
5  FRIEND
6      IN
7    DEED

In [69]:
import pandas as pd
data = pd.read_csv('/content/word-prevalence - word-prevalence.csv')
data_top = data.head(12)
print(data_top)

    Word  Rank  Frequency  Prevalence_Percentage Part_of_Speech
0    the     1   61872675                   5.62        Article
1     be     2   43235332                   3.93           Verb
2     to     3   29629472                   2.69    Preposition
3     of     4   27643564                   2.51    Preposition
4    and     5   26739678                   2.43    Conjunction
5      a     6   21743452                   1.98        Article
6     in     7   18451000                   1.68    Preposition
7   that     8   11537233                   1.05    Conjunction
8   have     9   11210058                   1.02           Verb
9      i    10   10118817                   0.92        Pronoun
10    it    11    9949665                   0.90        Pronoun
11   for    12    8782352                   0.80    Preposition

In [66]:
import pandas as pd
data = pd.read_csv('/content/word-prevalence - word-prevalence.csv')
n1 = 9
series = data["Word"]
top = series.head(n = n1)
print(top)

0     the
1      be
2      to
3      of
4     and
5       a
6      in
7    that
8    have
Name: Word, dtype: object

In [70]:
import pandas as pd
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [72]:
import pandas as pd
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
df = pd.DataFrame(data)
print(df[['Name', 'Qualification','Address']])

     Name Qualification    Address
0     Jai           Msc      Delhi
1  Princi            MA     Kanpur
2  Gaurav           MCA  Allahabad
3    Anuj           Phd    Kannauj

In [80]:
import pandas as pd
import pandas as pd
dataset=pd.read_excel('/content/Athletes.xlsx',  index_col ='Country')
first = dataset.loc["Switzerland"]
second=dataset.loc["Jamaica"]
print(first, "\n\n\n", second)

Athlete_ID            ATH_008
Name            Roger Federer
Sport                  Tennis
Gold_Medals                20
Total_Medals              103
Name: Switzerland, dtype: object


         Athlete_ID                     Name      Sport  Gold_Medals  \
Country
Jamaica    ATH_002               Usain Bolt  Athletics            8
Jamaica    ATH_010  Shelly-Ann Fraser-Pryce  Athletics            3

         Total_Medals
Country
Jamaica             8
Jamaica             8

In [89]:
import pandas as pd
data = pd.read_excel('/content/Athletes.xlsx', index_col ="Name")
row = dataset.iloc[0:10]
print(row)

              Athlete_ID                     Name       Sport  Gold_Medals  \
Country
United States    ATH_001           Michael Phelps    Swimming           23
Jamaica          ATH_002               Usain Bolt   Athletics            8
United States    ATH_003             Simone Biles  Gymnastics            4
United States    ATH_004            Katie Ledecky    Swimming            7
United States    ATH_005            Allyson Felix   Athletics            7
United States    ATH_006             LeBron James  Basketball            4
United States    ATH_007          Serena Williams      Tennis           23
Switzerland      ATH_008            Roger Federer      Tennis           20
Kenya            ATH_009           Eliud Kipchoge   Athletics            2
Jamaica          ATH_010  Shelly-Ann Fraser-Pryce   Athletics            3

               Total_Medals
Country
United States            28
Jamaica                   8
United States             7
United States            10
United States            11
United States             4
United States            39
Switzerland             103
Kenya                     4
Jamaica                   8

In [100]:
import pandas as pd
dataset = pd.read_excel("Athletes.xlsx")
first=dataset.loc[:,["Name","Total_Medals"]]
print(first)

                       Name  Total_Medals
0            Michael Phelps            28
1                Usain Bolt             8
2              Simone Biles             7
3             Katie Ledecky            10
4             Allyson Felix            11
5              LeBron James             4
6           Serena Williams            39
7             Roger Federer           103
8            Eliud Kipchoge             4
9   Shelly-Ann Fraser-Pryce             8
10           Caeleb Dressel            10
11         Mikaela Shiffrin             5
12              Shaun White             3
13                Chloe Kim             2
14           Novak Djokovic            98
15             Rafael Nadal            92
16        Cristiano Ronaldo            35
17             Lionel Messi            44
18              Naomi Osaka             7
19             Yuzuru Hanyu             2

In [94]:
import pandas as pd
dataset = pd.read_excel("/content/Athletes.xlsx", index_col ="Name")
row2 = dataset.iloc[[3, 1, 2]]
print(row2)

              Athlete_ID        Country       Sport  Gold_Medals  Total_Medals
Name
Katie Ledecky    ATH_004  United States    Swimming            7            10
Usain Bolt       ATH_002        Jamaica   Athletics            8             8
Simone Biles     ATH_003  United States  Gymnastics            4             7

In [1]:
import pandas as pd
data1 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi',
             	'Gaurav', 'Anuj', 'Princi', 'Abhi'],
        'Age':[27, 24, 22, 32,
           	33, 36, 27, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
               	'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                     	'B.Tech', 'B.com', 'Msc', 'MA']}
df = pd.DataFrame(data1)
print(df)
# Now we print the first entries in all the groups formed.
gk = df.groupby('Name')
gk.first()

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1    Anuj   24     Kanpur            MA
2     Jai   22  Allahabad           MCA
3  Princi   32    Kannuaj           Phd
4  Gaurav   33    Jaunpur        B.Tech
5    Anuj   36     Kanpur         B.com
6  Princi   27  Allahabad           Msc
7    Abhi   32    Aligarh            MA

        Age  Address Qualification
Name
Abhi     32  Aligarh            MA
Anuj     24   Kanpur            MA
Gaurav   33  Jaunpur        B.Tech
Jai      27   Nagpur           Msc
Princi   32  Kannuaj           Phd

In [2]:
df.groupby(['Name', 'Qualification'])
print(df.groupby(['Name', 'Qualification']).groups)
df.groupby(['Name']).sum()

{('Abhi', 'MA'): [7], ('Anuj', 'B.com'): [5], ('Anuj', 'MA'): [1], ('Gaurav', 'B.Tech'): [4], ('Jai', 'MCA'): [2], ('Jai', 'Msc'): [0], ('Princi', 'Msc'): [6], ('Princi', 'Phd'): [3]}

        Age           Address Qualification
Name
Abhi     32           Aligarh            MA
Anuj     60      KanpurKanpur       MAB.com
Gaurav   33           Jaunpur        B.Tech
Jai      49   NagpurAllahabad        MscMCA
Princi   59  KannuajAllahabad        PhdMsc

In [3]:
grp = df.groupby('Name')
for name, group in grp:
    print(name)
    print(group)
    print()

Abhi
   Name  Age  Address Qualification
7  Abhi   32  Aligarh            MA

Anuj
   Name  Age Address Qualification
1  Anuj   24  Kanpur            MA
5  Anuj   36  Kanpur         B.com

Gaurav
     Name  Age  Address Qualification
4  Gaurav   33  Jaunpur        B.Tech

Jai
  Name  Age    Address Qualification
0  Jai   27     Nagpur           Msc
2  Jai   22  Allahabad           MCA

Princi
     Name  Age    Address Qualification
3  Princi   32    Kannuaj           Phd
6  Princi   27  Allahabad           Msc

In [4]:
grp = df.groupby('Name')
grp.get_group('Jai')

  Name  Age    Address Qualification
0  Jai   27     Nagpur           Msc
2  Jai   22  Allahabad           MCA

In [5]:
import pandas as pd
import numpy as np
data1 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi',
             	'Gaurav', 'Anuj', 'Princi', 'Abhi'],
        'Age':[27, 24, 22, 32,
           	33, 36, 27, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
               	'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                     	'B.Tech', 'B.com', 'Msc', 'MA']}
df = pd.DataFrame(data1)
print(df)
grp1 = df.groupby('Name')
grp1.aggregate(np.sum)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1    Anuj   24     Kanpur            MA
2     Jai   22  Allahabad           MCA
3  Princi   32    Kannuaj           Phd
4  Gaurav   33    Jaunpur        B.Tech
5    Anuj   36     Kanpur         B.com
6  Princi   27  Allahabad           Msc
7    Abhi   32    Aligarh            MA

/tmp/ipykernel_1990/2689451452.py:14: FutureWarning: The provided callable <function sum at 0x7d65d193aa20> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.aggregate(np.sum)

        Age           Address Qualification
Name
Abhi     32           Aligarh            MA
Anuj     60      KanpurKanpur       MAB.com
Gaurav   33           Jaunpur        B.Tech
Jai      49   NagpurAllahabad        MscMCA
Princi   59  KannuajAllahabad        PhdMsc

In [6]:
import pandas as pd
import numpy as np
data1 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi',
              'Gaurav', 'Anuj', 'Princi', 'Abhi'],
        'Age':[27, 24, 22, 32,
            33, 36, 27, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                      'B.Tech', 'B.com', 'Msc', 'MA']}
df = pd.DataFrame(data1)
print(df)
grp1 = df.groupby('Name')
print(grp1)
print(grp1.agg([np.sum]))
print('============================')

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1    Anuj   24     Kanpur            MA
2     Jai   22  Allahabad           MCA
3  Princi   32    Kannuaj           Phd
4  Gaurav   33    Jaunpur        B.Tech
5    Anuj   36     Kanpur         B.com
6  Princi   27  Allahabad           Msc
7    Abhi   32    Aligarh            MA
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7d65add36600>
       Age           Address Qualification
       sum               sum           sum
Name
Abhi    32           Aligarh            MA
Anuj    60      KanpurKanpur       MAB.com
Gaurav  33           Jaunpur        B.Tech
Jai     49   NagpurAllahabad        MscMCA
Princi  59  KannuajAllahabad        PhdMsc
============================

/tmp/ipykernel_1990/2585394783.py:15: FutureWarning: The provided callable <function sum at 0x7d65d193aa20> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  print(grp1.agg([np.sum]))
/tmp/ipykernel_1990/2585394783.py:15: FutureWarning: The provided callable <function sum at 0x7d65d193aa20> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  print(grp1.agg([np.sum]))

In [7]:
grp = df.groupby('Name')
grp['Age'].agg([np.sum, np.mean, np.std])

/tmp/ipykernel_1990/4230543964.py:2: FutureWarning: The provided callable <function sum at 0x7d65d193aa20> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])
/tmp/ipykernel_1990/4230543964.py:2: FutureWarning: The provided callable <function mean at 0x7d65d193bb00> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])
/tmp/ipykernel_1990/4230543964.py:2: FutureWarning: The provided callable <function std at 0x7d65d193bc40> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])

        sum  mean       std
Name
Abhi     32  32.0       NaN
Anuj     60  30.0  8.485281
Gaurav   33  33.0       NaN
Jai      49  24.5  3.535534
Princi   59  29.5  3.535534

In [14]:
grp = df.groupby('Name')

# Applying both 'sum' and 'std' directly to the 'Age' column
result = grp.agg({'Age': ['sum', 'std']})
print(result)

       Age
       sum       std
Name
Abhi    32       NaN
Anuj    60  8.485281
Gaurav  33       NaN
Jai     49  3.535534
Princi  59  3.535534

In [15]:
grp = df.groupby('Name')
grp.agg({'Age' : 'sum', 'Score' : 'std'})

KeyError: "Column(s) ['Score'] do not exist"

In [16]:
import pandas as pd
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
df = pd.DataFrame(data)
df["Name"]= df["Name"].str.lower()
print(df)

     Name  Age    Address Qualification
0     jai   27      Delhi           Msc
1  princi   24     Kanpur            MA
2  gaurav   22  Allahabad           MCA
3    anuj   32    Kannauj           Phd

In [20]:
import pandas as pd
data = pd.read_csv('/word-prevalence - word-prevalence.csv')
data["Word"]= data["Word"].str.upper()
print(data)

    Word  Rank  Frequency  Prevalence_Percentage Part_of_Speech
0    THE     1   61872675                   5.62        Article
1     BE     2   43235332                   3.93           Verb
2     TO     3   29629472                   2.69    Preposition
3     OF     4   27643564                   2.51    Preposition
4    AND     5   26739678                   2.43    Conjunction
5      A     6   21743452                   1.98        Article
6     IN     7   18451000                   1.68    Preposition
7   THAT     8   11537233                   1.05    Conjunction
8   HAVE     9   11210058                   1.02           Verb
9      I    10   10118817                   0.92        Pronoun
10    IT    11    9949665                   0.90        Pronoun
11   FOR    12    8782352                   0.80    Preposition
12   NOT    13    7922289                   0.72         Adverb
13    ON    14    6925154                   0.63    Preposition
14  WITH    15    6902409                   0.63    Preposition
15    HE    16    6386470                   0.58        Pronoun
16    AS    17    6046747                   0.55    Conjunction
17   YOU    18    5971557                   0.54        Pronoun
18    DO    19    5132223                   0.47           Verb
19    AT    20    4976451                   0.45    Preposition
20  THIS    21    4846460                   0.44     Determiner
21   BUT    22    4390503                   0.40    Conjunction
22   HIS    23    4239845                   0.39        Pronoun
23    BY    24    4106552                   0.37    Preposition
24  FROM    25    3968254                   0.36    Preposition
25  THEY    26    3816223                   0.35        Pronoun
26    WE    27    3317730                   0.30        Pronoun
27   SAY    28    3237119                   0.29           Verb
28   HER    29    3163158                   0.29        Pronoun
29   SHE    30    2933092                   0.27        Pronoun

In [23]:
import pandas as pd
data = pd.read_csv("/word-prevalence - word-prevalence.csv")
data['Word']= data['Word'].replace('and', 'AND')
filter = data['Word']=="AND"
data.where(filter).dropna()

  Word  Rank   Frequency  Prevalence_Percentage Part_of_Speech
4  AND   5.0  26739678.0                   2.43    Conjunction

In [24]:
import pandas as pd
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
df = pd.DataFrame(data)
new = df["Address"].copy()
df["Name"]= df["Name"].str.cat(new, sep =", ")
print(df)

                Name  Age    Address Qualification
0        Jai, Nagpur   27     Nagpur           Msc
1     Princi, Kanpur   24     Kanpur            MA
2  Gaurav, Allahabad   22  Allahabad           MCA
3      Anuj, Kannuaj   32    Kannuaj           Phd

In [25]:
import pandas as pd
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
        'Age':[17, 14, 12, 52],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1,index=[0, 1, 2, 3])
df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])
print(df, "\n\n", df1)
frames = [df, df1]
res1 = pd.concat(frames)
print(res1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons
     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [26]:
import pandas as pd
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd'],
        'Mobile No': [97, 91, 58, 76]}
data2 = {'Name':['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
        'Age':[22, 32, 12, 52],
        'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons'],
        'Salary':[1000, 2000, 3000, 4000]}
df = pd.DataFrame(data1,index=[0, 1, 2, 3])
df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])
print(df, "\n\n", df1)
res2 = pd.concat([df, df1], axis=1, join='inner')
print(res2)
res2 = pd.concat([df, df1], axis=1, sort=False)
print(res2)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000
     Name  Age    Address Qualification  Mobile No    Name  Age    Address  \
2  Gaurav   22  Allahabad           MCA         58  Gaurav   22  Allahabad
3    Anuj   32    Kannuaj           Phd         76    Anuj   32    Kannuaj

  Qualification  Salary
2           MCA    1000
3           Phd    2000
     Name   Age    Address Qualification  Mobile No    Name   Age    Address  \
0     Jai  27.0     Nagpur           Msc       97.0     NaN   NaN        NaN
1  Princi  24.0     Kanpur            MA       91.0     NaN   NaN        NaN
2  Gaurav  22.0  Allahabad           MCA       58.0  Gaurav  22.0  Allahabad
3    Anuj  32.0    Kannuaj           Phd       76.0    Anuj  32.0    Kannuaj
6     NaN   NaN        NaN           NaN        NaN  Dhiraj  12.0  Allahabad
7     NaN   NaN        NaN           NaN        NaN  Hitesh  52.0    Kannuaj

  Qualification  Salary
0           NaN     NaN
1           NaN     NaN
2           MCA  1000.0
3           Phd  2000.0
6          Bcom  3000.0
7        B.hons  4000.0

In [34]:
import pandas as pd
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
        'Age':[17, 14, 12, 52],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1,index=[0, 1, 2, 3])
df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])
print(df, "\n\n", df1)
res = pd.concat([df,df1])
print(res)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons
     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [35]:
import pandas as pd
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
        'Age':[17, 14, 12, 52],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1,index=[0, 1, 2, 3])
df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])
print(df, "\n\n", df1)
frames = [df, df1 ]
res = pd.concat(frames, keys=['x', 'y'])
print(res)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons
       Name  Age    Address Qualification
x 0     Jai   27     Nagpur           Msc
  1  Princi   24     Kanpur            MA
  2  Gaurav   22  Allahabad           MCA
  3    Anuj   32    Kannuaj           Phd
y 4    Abhi   17     Nagpur         Btech
  5  Ayushi   14     Kanpur           B.A
  6  Dhiraj   12  Allahabad          Bcom
  7  Hitesh   52    Kannuaj        B.hons

In [36]:
import pandas as pd
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
df = pd.DataFrame(data1,index=[0, 1, 2, 3])
s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')
print(df, "\n\n", s1)
res = pd.concat([df, s1], axis=1)
print(res)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64
     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

In [38]:
import pandas as pd
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
print(df, "\n\n", df1)
res = pd.merge(df, df1, on='key')
print(res)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons
  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [39]:
import pandas as pd
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
print(df, "\n\n", df1)
res1 = pd.merge(df, df1, on=['key', 'key1'])
print(res1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons
  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [40]:
import pandas as pd
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
print(df, "\n\n", df1)
res = pd.merge(df, df1, how='left', on=['key', 'key1'])
print(res)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons
  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN